module exception;

nothrow:
@safe:

extern (C) void _d_assert(string file, uint line) {
    while (true) {
    }
}

extern (C) void _d_assert_msg(string msg, string file, uint line) {
    while (true) {
    }
}

extern (C) void _d_arraybounds(string file, uint line) {
    while (true) {
    }
}
